apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector: { matchLabels: { app: order-service } }
  template:
    metadata: { labels: { app: order-service } }
    spec:
      containers:
        - name: order-service
          image: sit722acrndax8i.azurecr.io/order-service:latest
          ports: [{ containerPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata: { name: order-svc }
spec:
  type: ClusterIP
  selector: { app: order-service }
  ports: [{ port: 8000, targetPort: 8000 }]
