name: CI - Build & Push to ACR

on:
  push:
    branches: [ "testing" ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  SHA: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Azure login via client secret (works without OIDC)
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - uses: docker/setup-buildx-action@v3

      # ---------- order-service ----------
      - name: Build & push order-service
        uses: docker/build-push-action@v6
        with:
          context: ./backend/order_service
          push: true
          tags: |
            ${{ env.REGISTRY }}/order-service:${{ env.SHA }}
            ${{ env.REGISTRY }}/order-service:testing

      # ---------- product-service ----------
      - name: Build & push product-service
        uses: docker/build-push-action@v6
        with:
          context: ./backend/product_service
          push: true
          tags: |
            ${{ env.REGISTRY }}/product-service:${{ env.SHA }}
            ${{ env.REGISTRY }}/product-service:testing

      # ---------- customer-service ----------
      - name: Build & push customer-service
        uses: docker/build-push-action@v6
        with:
          context: ./backend/customer_service
          push: true
          tags: |
            ${{ env.REGISTRY }}/customer-service:${{ env.SHA }}
            ${{ env.REGISTRY }}/customer-service:testing
